#!/usr/bin/env python3
"""
Report Generator — Markdown, SARIF, HTML output for audit reports.
Generates professional audit reports in multiple formats for CI/CD integration.
"""

import json
import os
from datetime import datetime
from typing import Dict, Any, List, Optional


def generate_markdown_report(report_dict: Dict[str, Any]) -> str:
    """Generate a professional Markdown audit report."""
    contract = report_dict.get("contract", {})
    scores = report_dict.get("scores", {})
    summary = report_dict.get("summary", {})
    analysis = report_dict.get("analysis", {})
    findings = report_dict.get("findings", [])
    
    address = contract.get("address", "Unknown")
    name = contract.get("name", "Unknown Contract")
    chain = contract.get("chain", "Unknown")
    score = scores.get("security_score", 0)
    risk = scores.get("risk_level", "UNKNOWN")
    
    # Risk badge
    risk_badges = {
        "CRITICAL": "🔴 CRITICAL",
        "HIGH": "🟠 HIGH",
        "MEDIUM": "🟡 MEDIUM",
        "LOW": "🔵 LOW",
        "SAFE": "🟢 SAFE",
    }
    risk_badge = risk_badges.get(risk, risk)
    
    lines = []
    lines.append(f"# Security Audit Report — {name}")
    lines.append("")
    lines.append(f"> Generated by **TSI-Audit-Scanner** on {report_dict.get('timestamp', datetime.now().isoformat())}")
    lines.append("")
    
    # Executive Summary
    lines.append("## Executive Summary")
    lines.append("")
    lines.append(f"| Metric | Value |")
    lines.append(f"|--------|-------|")
    lines.append(f"| **Contract** | `{address}` |")
    lines.append(f"| **Chain** | {chain} |")
    lines.append(f"| **Name** | {name} |")
    lines.append(f"| **Verified** | {'Yes' if contract.get('verified') else 'No'} |")
    lines.append(f"| **Security Score** | **{score}/100** |")
    lines.append(f"| **Risk Level** | {risk_badge} |")
    lines.append(f"| **Total Findings** | {summary.get('total_findings', 0)} |")
    lines.append(f"| **Duration** | {report_dict.get('duration_ms', 0):.0f}ms |")
    lines.append("")

    if contract.get("proxy"):
        lines.append(f"| **Proxy** | Yes → `{contract.get('implementation', 'Unknown')}` |")
    
    # Findings Breakdown
    lines.append("## Findings Breakdown")
    lines.append("")
    lines.append("| Severity | Count |")
    lines.append("|----------|-------|")
    lines.append(f"| 🔴 Critical | {summary.get('critical', 0)} |")
    lines.append(f"| 🟠 High | {summary.get('high', 0)} |")
    lines.append(f"| 🟡 Medium | {summary.get('medium', 0)} |")
    lines.append(f"| 🔵 Low | {summary.get('low', 0)} |")
    lines.append(f"| ⚡ Gas | {summary.get('gas', 0)} |")
    lines.append(f"| ℹ️ Info | {summary.get('info', 0)} |")
    lines.append("")
    
    # Analysis
    lines.append("## Contract Analysis")
    lines.append("")
    interfaces = analysis.get("interfaces", [])
    protocols = analysis.get("defi_protocols", [])
    funcs = analysis.get("functions", {})
    
    lines.append(f"- **Interfaces:** {', '.join(interfaces) if interfaces else 'None detected'}")
    lines.append(f"- **DeFi Protocols:** {', '.join(protocols) if protocols else 'None detected'}")
    lines.append(f"- **Access Control:** {analysis.get('access_control') or 'Unknown'}")
    lines.append(f"- **Functions:** {funcs.get('total', 0)} total, {funcs.get('external', 0)} external, {funcs.get('payable', 0)} payable, {funcs.get('admin', 0)} admin")
    lines.append("")
    
    # Detailed Findings
    if findings:
        lines.append("## Detailed Findings")
        lines.append("")
        
        severity_order = ["CRITICAL", "HIGH", "MEDIUM", "LOW", "GAS", "INFO"]
        for sev in severity_order:
            sev_findings = [f for f in findings if f.get("severity") == sev]
            if not sev_findings:
                continue
            
            sev_icon = {"CRITICAL": "🔴", "HIGH": "🟠", "MEDIUM": "🟡", "LOW": "🔵", "GAS": "⚡", "INFO": "ℹ️"}.get(sev, "")
            lines.append(f"### {sev_icon} {sev} ({len(sev_findings)})")
            lines.append("")
            
            for i, f in enumerate(sev_findings, 1):
                lines.append(f"#### {i}. {f.get('title', 'Unknown')}")
                lines.append("")
                lines.append(f"- **ID:** `{f.get('id', '')}`")
                lines.append(f"- **Category:** {f.get('category', '')}")
                if f.get("line_number"):
                    lines.append(f"- **Location:** Line {f['line_number']}")
                lines.append(f"- **Confidence:** {f.get('confidence', 1.0):.0%}")
                lines.append("")
                lines.append(f"**Description:** {f.get('description', '')}")
                lines.append("")
                lines.append(f"**Recommendation:** {f.get('recommendation', '')}")
                lines.append("")
                
                if f.get("code_snippet"):
                    lines.append("```solidity")
                    lines.append(f["code_snippet"])
                    lines.append("```")
                    lines.append("")
    else:
        lines.append("## Findings")
        lines.append("")
        lines.append("No security issues detected. Contract appears safe.")
        lines.append("")
    
    # Footer
    lines.append("---")
    lines.append("")
    lines.append(f"*Report generated by TSI-Audit-Scanner v2.0 | {len(findings)} patterns checked | Protection-first detection engine*")
    
    return "\n".join(lines)


def generate_sarif_report(report_dict: Dict[str, Any]) -> Dict[str, Any]:
    """
    Generate SARIF v2.1.0 output for CI/CD integration.
    Compatible with GitHub Code Scanning, Azure DevOps, and other SARIF consumers.
    """
    findings = report_dict.get("findings", [])
    contract = report_dict.get("contract", {})
    
    # Map severity to SARIF levels
    severity_map = {
        "CRITICAL": "error",
        "HIGH": "error",
        "MEDIUM": "warning",
        "LOW": "note",
        "GAS": "note",
        "INFO": "none",
    }
    
    rules = []
    results = []
    seen_rules = set()
    
    for finding in findings:
        rule_id = finding.get("id", "UNKNOWN")
        
        # Add rule definition (deduplicated)
        if rule_id not in seen_rules:
            seen_rules.add(rule_id)
            rules.append({
                "id": rule_id,
                "name": finding.get("title", ""),
                "shortDescription": {"text": finding.get("title", "")},
                "fullDescription": {"text": finding.get("description", "")},
                "helpUri": f"https://swcregistry.io/docs/{rule_id}" if rule_id.startswith("SWC-") else None,
                "defaultConfiguration": {
                    "level": severity_map.get(finding.get("severity", ""), "warning")
                },
                "properties": {
                    "category": finding.get("category", ""),
                    "confidence": finding.get("confidence", 1.0),
                }
            })
        
        # Build result
        result = {
            "ruleId": rule_id,
            "level": severity_map.get(finding.get("severity", ""), "warning"),
            "message": {
                "text": f"{finding.get('description', '')}. Recommendation: {finding.get('recommendation', '')}"
            },
            "properties": {
                "confidence": finding.get("confidence", 1.0),
                "severity_weight": finding.get("severity_weight", 0),
            }
        }
        
        # Add location if line number is known
        if finding.get("line_number"):
            result["locations"] = [{
                "physicalLocation": {
                    "artifactLocation": {
                        "uri": contract.get("address", "unknown"),
                        "uriBaseId": contract.get("chain", "ethereum")
                    },
                    "region": {
                        "startLine": finding["line_number"]
                    }
                }
            }]
        
        results.append(result)
    
    sarif = {
        "$schema": "https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json",
        "version": "2.1.0",
        "runs": [{
            "tool": {
                "driver": {
                    "name": "TSI-Audit-Scanner",
                    "version": "2.0.0",
                    "informationUri": "https://github.com/TSI-Audit-Scanner",
                    "rules": rules,
                }
            },
            "results": results,
            "invocations": [{
                "executionSuccessful": True,
                "endTimeUtc": report_dict.get("timestamp", datetime.now().isoformat()),
            }]
        }]
    }
    
    return sarif


def save_report(report_dict: Dict[str, Any], output_path: str, fmt: str = "json"):
    """Save report in specified format."""
    os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)
    
    if fmt == "markdown" or fmt == "md":
        content = generate_markdown_report(report_dict)
        if not output_path.endswith(".md"):
            output_path += ".md"
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(content)
    elif fmt == "sarif":
        content = generate_sarif_report(report_dict)
        if not output_path.endswith(".sarif"):
            output_path += ".sarif"
        with open(output_path, "w", encoding="utf-8") as f:
            json.dump(content, f, indent=2)
    else:  # json
        with open(output_path, "w", encoding="utf-8") as f:
            json.dump(report_dict, f, indent=2)
    
    return output_path
